### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by shiftgeist** [dracula/mattermost#1]
https://draculatheme.com/mattermost responds with an `404 Page not found` error.

**Comment by milouse** [comment]
Very weird… I never pay attention to the dracula home page. After a quick search on the site project, I find nothing about mattermost, as if the page was never included. I don't remember at all if it has been included or note. @zenorocha can you confirm that this page never existed? I can do the PR for you if necessary.

**Comment by shiftgeist** [comment]
Its bin a while `*push*`

**Comment by zenorocha** [comment]
This has been finally fixed: https://draculatheme.com/mattermost

Thanks @shiftgeist for reporting.

Sorry for taking so long @milouse
